2_разметка по БЭМ
htmlacademy-adaptive/998653-sedona-23 pull request #4
Opened 2021-07-27 12:26 UTC by nata07-erbet

2021-08-09 18:29 UTC, avylando requested changes
1. Все изображения нужно загрузить в source/img и подключать их оттуда
Так как гитхаб конечно ничего не знает про твои локальные картинки)

2. Структура и имена страниц должны быть такими или похожими (index.html - это всегда главная)
```
- source
|- - index.html
|- - form.html
|- - catalog.html
```

И поправь, пожалуйста, остальные замечания

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:07:27.html
> +<!DOCTYPE html>
Что-то с именами файлов у тебя напутано) должно быть три страницы в source - index.html, photo.html, form.html

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +      <img class="page-header__logo" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/Layer 2 1.svg"
1. Оригинальная ссылка на картинку) картинки нужно загрузить в репозиторий и указать относительный путь к ним

2. у тебя у a и img одинаковое название класса, назови их по-разному

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +      width="101,7px" height="84px" alt="Проект Седона">
размеры картинкам задавай в целых числах и без указания единиц измерения 
```
width="102" height="84"
```

это касается всех картинок

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                <li class="main-nav__item main-nav--current">
поправь `main-nav__item--current`

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                    <a class="main-nav__link" href="photo&video.html">
ссылки в меню должны быть правильными

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +              </p>
закрывающий тег неправильный, должен быть h3

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                <div class="reasons__first first">
first - не очень удачное название для бэм-блока. Лучше не завязываться на порядок блоков, так как он может поменяться, а давать им более подходящие их содержанию названия
Да и на самом деле у тебя тут есть два практически одинаковых блока с фото и текстом
![Снимок](https://user-images.githubusercontent.com/30809044/128753701-d31fa8e4-19cf-40c0-884b-b9e1c0b31088.PNG)
![Снимок2](https://user-images.githubusercontent.com/30809044/128753711-2acb5d78-7554-43bd-b5cf-8d1f904d4241.PNG)

можно сделать им общий бэм-класс и добавить каждому модификатор, например illustration illustration--city и illustration--bridge

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                <div class="first__points points">
Этот блок уже не внутри first, он относится к reasons

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                    <h3 class="second__titile">ТАМ ЕСТЬ МОСТ ДЬЯВОЛА</h3>
Опечатка `second__title`

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +            </div>
А вот эти штуки я бы объединил одним бэм-блоком, так как у них здесь идентичные стили
И можно даже в список их поместить
А назвать например other-reasons или advantages

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +              </div>
map лучше вынеси в отдельную section
Это все-таки самостоятельный блок + так удобнее будет делать сетку

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +              </div>
и img тут не нужен, карту сделаем через background-image

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                      <a class="social-link social-link--twitter" href="https://twitter.com/sedona">
Поправь тут и везде `social__link social__link--twitter`

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                        <img class="social-link__icon" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/icon-twitter.svg.png" width="17,5px"  height="14,57px"> <!--я не помимаюБ почему не отображ
Надеюсь это опечатка?) social-link не надо делать отдельным бэм-блоком
просто `social__icon`

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                    <a class="social-link social-link--twitter" href="https://facebook.com/sedona">
Тут уже не твиттер)

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                    <a class="social-link social-link--twitter" href="https://yuotube.com/sedona">
и тут

2021-08-09 18:29 UTC, avylando commented on source/sedona_2021:08:07.html
> +                            <img class="points__icon" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/icon-gift.svg.png" width="39px" height="36,83px" alt="подарок"> <!--я понимаю, что иконки мо
Да, вставлять можешь и так, но выгрузить нужно именно в формате svg
сейчас у тебя png

2021-08-16 12:41 UTC, closed without merging

2021-08-30 10:51 UTC, nata07-erbet commented on source/sedona_2021:08:07.html
> +      <img class="page-header__logo" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/Layer 2 1.svg"
<body class="page__body">
  <header class="page-header">
    <a class="page-header__logo">
      <img class="page-header__logo-image" src="/Users/erbetnataly/998653-sedona-23/source/img/logotype-mobile.svg"
      width="102px" height="84px" alt="Проект Седона"> #7

2021-08-30 10:57 UTC, nata07-erbet commented on source/sedona_2021:08:07.html
> +      width="101,7px" height="84px" alt="Проект Седона">
``` <body class="page__body">
  <header class="page-header">
    <a class="page-header__logo">
      <img class="page-header__logo-image" src="/Users/erbetnataly/998653-sedona-23/source/img/logotype-mobile.svg"
      width="102px" height="84px" alt="Проект Седона">
```