Module2 task1
htmlacademy-adaptive/998653-sedona-23 pull request #7
Opened 2021-08-16 16:47 UTC by nata07-erbet

разметка главной страницы

2021-08-16 16:48 UTC, nata07-erbet commented
разметка главной страницы

2021-08-20 17:09 UTC, avylando requested changes
Не вижу изменений по сравнению с https://github.com/htmlacademy-adaptive/998653-sedona-23/pull/4

Тот ПР не надо было закрывать, но раз уж закрыла то внеси все правки по комментам оттуда в этот реквест

2021-08-20 17:09 UTC, avylando commented on source/index.html
> +      <img class="page-header__logo" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/Layer 2 1.svg"
Одинаковые классы у ссылки и картинки, нужно назвать по-разному

2021-08-31 11:46 UTC, avylando reviewed
Привет! Очень долго сидим с этим заданием, давай так - ты эти изменения снова запушишь, так как у тебя сейчас их нет в актуальной версии и я приму так

Все замечания которые я написал выше нужно будет поправить в следующем задании

2021-08-31 11:46 UTC, avylando commented on index.html
> +      <img class="page-header__logo" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/Layer 2 1.svg"
ссылки и названия картинок поправить

2021-08-31 11:46 UTC, avylando commented on index.html
> +      <img class="page-header__logo" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/Layer 2 1.svg"
Также у тебя дублируется класс page-header__logo

2021-08-31 11:46 UTC, avylando commented on index.html
> +      width="101,7px" height="84px" alt="Проект Седона">
задавай width в целых числах

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +  <link rel="stylesheet" href="index.css">
файл должен называться style.css

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +      <img class="page-header__logo-image" src="/HTML/998653-sedona-23/source/img/logotype-mobile .svg"
Неправильная ссылка
Правильно так - `img/logotype-mobile.svg`

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +          <img class="page-main__image" src="/HTML/998653-sedona-23/source/img/back-mobile.png"
`img/back-mobile.svg`

Но название картинки непонятное и формат неправильный (фотографии у нас в формате jpg. должны быть), сделай ее main-poster.jpg

2021-08-31 11:46 UTC, avylando commented on source/index.html
>        </div>
Это что за текст картинкой?) Если это текст который на самой картинке, то он является ее частью и не надо его экспортировать отдельным файлом

Нужно сделать экспорт сразу двух слоев в один файл, вот таким образом
![Снимок экрана 2021-08-31 в 14 34 02](https://user-images.githubusercontent.com/30809044/131495571-78c7853e-203c-41b9-9420-b10960f85a7d.png)

2021-08-31 11:46 UTC, avylando commented on source/index.html
>        </div>
Эти треугольники тоже удали, такие маски обычно делаются через псевдоэлементы в css

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                    <h3 class="illustration__titile">НАСТОЯЩИЙ ГОРОДОК</h3>
*illustration__title

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                        <img class="illustration__city-image" src="/HTML/998653-sedona-23/source/img/photo-city@1x 1 .png"
Поправить ссылку и формат - jpg

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                    <div class="illustration__image">
image-wrapper лучше

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                        <img class="illustration__city-image" src="/HTML/998653-sedona-23/source/img/photo-city@1x 1 .png"
а здесь тогда просто image

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                <div class="house__points points">
Откуда взялся блок house?

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                    <div class="illustration__image">
illustration__image-wrapper

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                        <img class="illustration__city-brige" src="/HTML/998653-sedona-23/source/img/photo-bridge@1x 1 .png"
illustration__image

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                    <h3 class="other-reasons__titile">НЕБОЛЬШАЯ ПЛОЩАДЬ</h3>
*title

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                  <div class="other-reasons other-reasons--square">
Ошибка БЭМ - это элемент блока other-reasons, у него должно быть название, например
`other-reasons__wrapper other-reasons__wrapper--square`

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                      <h3 class="other-reasons__titile">КРАСИВАЯ ДОРОГА</h3>
*title

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                      <h3 class="other-reasons__titile">МАЛО ТУРИСТОВ</h3>
*title

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                  <div class="other-reasons other-reasons--square">
Нижние блоки аналогично

2021-08-31 11:46 UTC, avylando commented on source/index.html
>                </p>
тут элемент p лишний

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                        <div class="social__link-layout">
Зачем нужен этот div? его можно убрать

2021-08-31 11:46 UTC, avylando commented on source/index.html
> +                          <img class="social__link-icon" src="/HTML/998653-sedona-23/source/img/icon-twitter.svg"
лучше `social__icon`, без link

так лучше читаемость, иначе у тебя появляется много классов с похожими названиями и становится сложно ориентироваться

2021-09-02 10:04 UTC, nata07-erbet commented on index.html
> +      <img class="page-header__logo" src="/Users/erbetnataly/Documents/Яндекс.Диск/SEDONA/Layer 2 1.svg"
```<a class="page-header__logo">
      <img class="page-header__logo-image" src="logotype-mobile.svg"
      width="102px" height="84px" alt="Проект Седона">
    </a>  
```

2021-09-02 10:05 UTC, nata07-erbet commented on index.html
> +      width="101,7px" height="84px" alt="Проект Седона">
исправлено

2021-09-02 10:07 UTC, nata07-erbet commented on source/index.html
> +  <link rel="stylesheet" href="index.css">
<link rel="stylesheet" href="style.css">

2021-09-02 10:09 UTC, nata07-erbet commented on source/index.html
> +      <img class="page-header__logo-image" src="/HTML/998653-sedona-23/source/img/logotype-mobile .svg"
`<img class="page-header__logo-image" src="logotype-mobile.svg"
      width="102px" height="84px" alt="Проект Седона">`

2021-09-02 10:12 UTC, nata07-erbet commented on source/index.html
> +                      <h3 class="other-reasons__titile">КРАСИВАЯ ДОРОГА</h3>
`<h3 class="other-reasons__title">КРАСИВАЯ ДОРОГА</h3>`

2021-09-02 10:13 UTC, nata07-erbet commented on source/index.html
> +                      <h3 class="other-reasons__titile">МАЛО ТУРИСТОВ</h3>
` <h3 class="other-reasons__title">МАЛО ТУРИСТОВ</h3>`

2021-09-02 10:14 UTC, nata07-erbet commented on source/index.html
>                </p>
`<div class="page-footer__hashtag hashtag">
                  #VISITSEDONA
          </div>`

2021-09-02 10:21 UTC, nata07-erbet commented on source/index.html
> +                          <img class="social__link-icon" src="/HTML/998653-sedona-23/source/img/icon-twitter.svg"
` <img class="social__icon" src="icon-facebook.svg"`

2021-09-02 14:33 UTC, avylando approved these changes

2021-09-02 14:33 UTC, merged